id: AA735ABC6
title: 'Beautiful Clouds of Blessings: A Prayer to the Lineage Masters of the Heart
  Essence of the Vast Expanse from the Great Perfection'
type: translation
pechas:
- I84705A25
- IB2341521
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:36:49.242838
  last_modified_at: 2023-01-04 11:36:49.242849
  collections:
  - Dilgo Khyentse Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I84705A25/34E5: 1F35
  IB2341521/2C54: 1F35
